"""
Knowledge Distillation Training Pipeline for Custom Draft Transformer.
Trains the student model (~75M parameters) on next-token prediction over the corpus
generated by the teacher (Llama-3.1-8B-Instruct).
Supports GPU acceleration (CUDA) and CPU fallback.
"""

import os
import sys
from pathlib import Path

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import json
import time
import math
import argparse
from typing import List, Dict

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from transformers import AutoTokenizer
from training.draft_arch import DraftTransformer, DraftTransformerConfig
from training.export_draft_model import export_checkpoint

class DistillationDataset(Dataset):
    """Dataset loading tokenized prompt-completion pairs from JSONL corpus."""
    def __init__(self, jsonl_path: Path, tokenizer, max_seq_len: int = 512):
        self.samples = []
        self.tokenizer = tokenizer
        self.max_seq_len = max_seq_len

        if not jsonl_path.exists():
            raise FileNotFoundError(f"Distillation dataset not found at: {jsonl_path}")

        with open(jsonl_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                data = json.loads(line)
                full_text = f"<|start_header_id|>user<|end_header_id|>\n\n{data['prompt']}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n{data['completion']}<|eot_id|>"
                token_ids = self.tokenizer.encode(full_text)
                if len(token_ids) > 8:
                    self.samples.append(token_ids[:max_seq_len])

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        return self.samples[idx]

def collate_fn(batch: List[List[int]], pad_token_id: int = 128001):
    max_len = max(len(s) for s in batch)
    input_ids = []
    labels = []
    
    for seq in batch:
        padded = seq + [pad_token_id] * (max_len - len(seq))
        inp = padded[:-1]
        lbl = padded[1:]
        lbl = [t if t != pad_token_id else -100 for t in lbl]
        input_ids.append(inp)
        labels.append(lbl)

    return torch.tensor(input_ids, dtype=torch.long), torch.tensor(labels, dtype=torch.long)

def train(
    data_path: Path,
    output_checkpoint: Path,
    epochs: int = 10,
    batch_size: int = 4,
    learning_rate: float = 3e-4,
    weight_decay: float = 0.01,
    max_seq_len: int = 512,
    device_str: str = "auto",
    tokenizer_name: str = "checkpoints/tokenizer"
):
    if device_str == "auto":
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(device_str)

    print(f"[*] Training on device: {device}")
    
    # Load tokenizer locally if available
    local_tok = Path("checkpoints/tokenizer")
    if local_tok.exists() and (local_tok / "tokenizer.json").exists():
        tokenizer_path = str(local_tok)
    else:
        tokenizer_path = tokenizer_name

    print(f"[*] Loading tokenizer from: {tokenizer_path}...")
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_path, local_files_only=Path(tokenizer_path).exists())
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = 128001 # Llama 3.1 default <|reserved_special_token_0|> / pad

    print(f"[*] Loading dataset from: {data_path}...")
    dataset = DistillationDataset(data_path, tokenizer, max_seq_len=max_seq_len)
    print(f"    Loaded {len(dataset)} training sequences.")

    loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=True,
        collate_fn=lambda b: collate_fn(b, pad_token_id=tokenizer.pad_token_id)
    )

    # Initialize Draft Transformer Model
    config = DraftTransformerConfig(
        vocab_size=len(tokenizer),
        hidden_dim=512,
        num_layers=5,
        num_heads=8,
        head_dim=64,
        intermediate_dim=1536,
        max_seq_len=max_seq_len,
        tie_word_embeddings=True
    )
    model = DraftTransformer(config).to(device)
    param_count = model.count_parameters()
    print(f"[OK] Initialized DraftTransformer with {param_count:,} parameters (~{param_count/1e6:.1f}M).")

    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=weight_decay, betas=(0.9, 0.95))
    total_steps = len(loader) * epochs
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max(total_steps, 1), eta_min=1e-5)
    loss_fn = nn.CrossEntropyLoss(ignore_index=-100)

    model.train()
    best_loss = float("inf")
    start_time = time.time()

    for epoch in range(1, epochs + 1):
        epoch_loss = 0.0
        step_count = 0

        for step, (input_ids, labels) in enumerate(loader):
            input_ids = input_ids.to(device)
            labels = labels.to(device)

            optimizer.zero_grad()
            logits, _ = model(input_ids)
            
            loss = loss_fn(logits.view(-1, config.vocab_size), labels.view(-1))
            loss.backward()

            # Gradient clipping
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            scheduler.step()

            epoch_loss += loss.item()
            step_count += 1

        avg_loss = epoch_loss / max(step_count, 1)
        perplexity = math.exp(min(avg_loss, 20))
        print(f"Epoch [{epoch:02d}/{epochs:02d}] - Loss: {avg_loss:.4f} | PPL: {perplexity:.2f} | LR: {scheduler.get_last_lr()[0]:.2e}")

        if avg_loss < best_loss:
            best_loss = avg_loss
            export_checkpoint(model, output_checkpoint, tokenizer_name=tokenizer_path)

    elapsed = time.time() - start_time
    print(f"\n[OK] Training completed in {elapsed:.1f}s. Best Loss: {best_loss:.4f}")
    print(f"[OK] Checkpoint saved at: {output_checkpoint}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train Distillation Draft Model")
    parser.add_argument("--data", type=str, default="data/distillation_corpus.jsonl", help="Path to JSONL data")
    parser.add_argument("--output", type=str, default="checkpoints/draft_model.pt", help="Checkpoint output path")
    parser.add_argument("--tokenizer", type=str, default="checkpoints/tokenizer", help="Tokenizer path")
    parser.add_argument("--epochs", type=int, default=5, help="Number of epochs")
    parser.add_argument("--batch-size", type=int, default=2, help="Batch size")
    parser.add_argument("--lr", type=float, default=3e-4, help="Learning rate")
    parser.add_argument("--device", type=str, default="auto", help="Device (cuda, cpu, auto)")
    args = parser.parse_args()

    train(
        data_path=Path(args.data),
        output_checkpoint=Path(args.output),
        tokenizer_name=args.tokenizer,
        epochs=args.epochs,
        batch_size=args.batch_size,
        learning_rate=args.lr,
        device_str=args.device
    )
